#!/bin/sh
#
# Update the files directory (which contains pdfs etc) from svn/dyalog/docbin
# This presupposes that the directory "files" contains a checkout of docbin/version/documnentation
# and files/sharpplot contains a checkout of the sharpplot release directory
#
# AWS 2014-06-25
# AWS 2016-08-26 Previous version had somehow merged all previous versions into one script
# AWS 2025-07-21 Prepare for merging into new workflow
#
# It is assumed that all temporary files start with $(basename $0).
#
# Logic is:
#
#	ensure that filelist and the contents of the directory match
#	delete anything that's not wanted

#set -x
set -e

Exit ()
{
	EC=$1 ; shift
	rm -f ${TMPFILE}*
	echo $*
	exit $EC
}

FILESDIR="files"
SHARPPLOTDIR="./sharpplot"		# Relative to $FILESDIR
SHARPPLOTCHM="sharpplot.chm"
READMEDIR="./readmes"
SETUPREADME="setup_readme.htm"
DYALOGREADME="dyalog_readme.htm"
FILELISTFILE="./filelist.txt"

TMPFILE="$(basename $0).$$"
TMPFILELIST="$TMPFILE.filelist.$$"

[ $# -ne 1 ] && Exit 1 "Usage: $0 version"
VERSION=$1

# 1. move sharplot.chm up one level and delete .svn, readmes and sharpplot directories
echo "Move sharplot.chm, setup_readme and dyalog_readme  up one level and delete .svn, readmes and sharpplot directories .."
cd $FILESDIR || Exit 2 "Unable to cd to $FILESDIR after exporting from svn"
[ ! -f $SHARPPLOTDIR/$SHARPPLOTCHM ] && Exit 2 "No $SHARPPLOTDIR/$SHARPPLOTCHM file exists; bailing"
[ ! -f $READMEDIR/$SETUPREADME ] && Exit 2 "No $READMEDIR/$SETUPREADME file exists; bailing"
[ ! -f $READMEDIR/$DYALOGREADME ] && Exit 2 "No $READMEDIR/$DYALOGREADME file exists; bailing"
[ ! -f $FILELISTFILE ] && Exit 2 "No $FILELISTFILE; bailing"
mv $SHARPPLOTDIR/$SHARPPLOTCHM $READMEDIR/$SETUPREADME $READMEDIR/$DYALOGREADME .
rm -rf .svn $SHARPPLOTDIR $READMEDIR

# 2. Sanity check: all files in the file list should be present
echo "Check that all files in filelist are present .."
# We have to cope with $SHARPPLOTCHM, $SETUPREADME and $DYALOGREADME.  The simplest way is to add them to
# $FILELISTFILE at this point ..
echo "./$SHARPPLOTCHM\tweb" >>$FILELISTFILE
echo "./$SETUPREADME\tweb" >>$FILELISTFILE
echo "./$DYALOGREADME\tweb" >>$FILELISTFILE
egrep -v "^#|^$|^[ 	]*$" $FILELISTFILE >$TMPFILE && mv $TMPFILE $FILELISTFILE
[ 0 -eq $(wc -l $FILELISTFILE | awk '{print $1}') ] && Exit 2 "$FILELISTFILE is empty"

sed 's/\t.*$//' $FILELISTFILE | sort >$TMPFILELIST

find . -type f | grep -v "$TMPFILE" | sort >$TMPFILE
comm -2 -3 $TMPFILELIST $TMPFILE >$TMPFILE.missing
comm -1 -3 $TMPFILELIST $TMPFILE >$TMPFILE.new
[ -s $TMPFILE.missing ] && { echo "BAIL: $FILELISTFILE includes files which are not in SVN" ; cat $TMPFILE.missing ; Exit 1; }
[ -s $TMPFILE.new ] && { echo "BAIL: SVN includes files that are not in $FILELISTFILE" ; cat $TMPFILE.new ; Exit 2; }

# 3. Only keep files that are for the web
echo "Remove files that are not to appear on docs.dyalog.com .."
grep -v "\sweb$" $FILELISTFILE | sed 's/\t.*$//' | sort >$TMPFILELIST
cat $TMPFILELIST | while read FILE
do
	rm -f "${FILE}"
done

# 4. Update the version number in header.html
echo "Update version number in header.html .."
sed "s/DYALOG_VERSION/$VERSION/g" theme/header.html > $TMPFILE && cat $TMPFILE >theme/header.html

# 5. cp htaccess file in place
echo "Create $FILESDIR/.htaccess .."
cp theme/htaccess.txt ./.htaccess && chmod 644 ./.htaccess

Exit 0 "Done"
