site_name: Release Notes V19.0
theme:
  favicon: img/favicon-32.png
  logo: img/dyalog-logo-2025_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - Introduction:
      - Key Features: introduction/key-features.md
      - Extension to Native File Functions: introduction/extension-to-native-file-functions.md
      - Lexical Scope in Scripts: introduction/lexical-scope-in-scripts.md
      - Session Gutter: introduction/session-gutter.md
      - Source as Typed: introduction/source-as-typed.md
      - Bug Fixes: introduction/bug-fixes.md
      - Announcements: introduction/announcements.md
      - System Requirements: introduction/requirements.md
      - Interoperability: introduction/interoperability.md
  - Configuration Parameters:
      - New or Changed Configuration Parameters: configuration-parameters/changes-to-configuration-parameters.md
      - DYALOG_GUTTER_ENABLE: configuration-parameters/dyalog-gutter-enable.md
      - DYALOG_DISCARD_FN_SOURCE: configuration-parameters/dyalog-discard-fn-source.md
      - DYALOG_INITSESSION: configuration-parameters/dyalog-initsession.md
      - DyalogLink: configuration-parameters/dyaloglink.md
      - DyalogStartup_X: configuration-parameters/dyalogstartup-x.md
      - DyalogStartupSE: configuration-parameters/dyalogstartupse.md
      - Log_File: configuration-parameters/log-file.md
  - Language Reference Changes:
      - Language Changes: language-reference-changes/language-enhancements.md
      - File Hold: language-reference-changes/fhold.md
      - Fix Script: language-reference-changes/fix.md
      - Allocate Token Range: language-reference-changes/talloc.md
      - Memory Manager Statistics: language-reference-changes/memory-manager-statistics.md
      - Enable Compression of Large Components: language-reference-changes/enable-compression-of-large-components.md
      - Discard Source Information: language-reference-changes/discard-source-information.md
      - Discard Source Code: language-reference-changes/discard-source-code.md
      - Hash Table Size: language-reference-changes/hash-table-size.md
      - Lookup Table Size: language-reference-changes/lookup-table-size.md
  - Object Reference Changes:
      - AllowContextMenu: object-reference-changes/allowcontextmenu.md
      - ExecuteJavaScript: object-reference-changes/executejavascript.md
      - GetZoomLevel: object-reference-changes/getzoomlevel.md
      - IsLoading: object-reference-changes/isloading.md
      - LoadEnd: object-reference-changes/loadend.md
      - SetZoomLevel: object-reference-changes/setzoomlevel.md
